name: Build kernel deb packages
on:
  workflow_dispatch:
  push:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        version: ["5.19.0"]
    name: Build kernel
    runs-on: ubuntu-22.04
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 4096
          swap-size-mb: 512
          remove-dotnet: 'true'
          remove-android: 'true'

      - name: Checkout
        uses: actions/checkout@v3

      - name: start docker and build 
        run: |
          ls -al ${{ github.workspace }} 
          chmod +x ${{ github.workspace }}/docker-entrypoint.sh 
          docker run --rm --env VERSION=${{ matrix.version }} \
            -v ${{ github.workspace }}/linux-${{ matrix.version }}/:/linux-${{ matrix.version }}/ \
            -v ${{ github.workspace }}/config-${{ matrix.version }}:/config-${{ matrix.version }} \
            -v ${{ github.workspace }}/docker-entrypoint.sh:/docker-entrypoint.sh \
            -v ${{ github.workspace }}/patch.d/:/patch.d/ \
            gcc:bullseye "/docker-entrypoint.sh"

      - name: Build
        run: bash build_action.sh

      - name: Artifact
        uses: actions/upload-artifact@v3
        with:
          name: linux-${{ matrix.version }}
          path: ${{ github.workspace }}/linux-${{ matrix.version }}/