name: Build kernel deb packages
on:
  workflow_dispatch:
  push:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    name: Build kernel
    runs-on: ubuntu-22.04
    container:
      image: gcc:latest
      options: --user root
    steps:
      - name: Install sudo
        run: |
          apt-get update
          apt install -y sudo
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 4096
          swap-size-mb: 512
          remove-dotnet: 'true'
          remove-android: 'true'
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: bash build_action.sh

      - name: Artifact
        uses: actions/upload-artifact@v2
        with:
          name: artifact
          path: ${{ github.workspace }}/artifact/