name: Build kernel deb packages
on:
  workflow_dispatch:
  push:


jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        version: ["5.18.19", "5.19.0", "5.19.1"]
        include:
          - version: d521bc0a0f7c
            kernel_fetch_url: git://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git
            config: config-5.19.0
    name: Build kernel
    runs-on: ubuntu-22.04
    steps:
      - name: Update and Upgrade
        run: |
          sudo apt-get update
          sudo apt-get upgrade -y
          sudo apt install zstd tree -y
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 4096
          swap-size-mb: 512
          remove-dotnet: 'true'
          remove-android: 'true'

      - name: Checkout
        uses: actions/checkout@v3

      - name: start docker and build 
        run: |
          ls -al ${{ github.workspace }} 
          chmod +x ${{ github.workspace }}/fetch-config.sh
          VERSION=${{ matrix.version }} CONFIG=${{ matrix.config }} source ./fetch-config.sh
          chmod +x ${{ github.workspace }}/docker-entrypoint.sh 
          docker run --rm --user root --env VERSION=${{ matrix.version }} \
            --env KERNEL_FETCH_URL=${{ matrix.kernel_fetch_url }} \
            -v ${{ github.workspace }}/linux-${{ matrix.version }}/:/linux-${{ matrix.version }}/ \
            -v ${{ github.workspace }}/config-${{ matrix.version }}:/config-${{ matrix.version }} \
            -v ${{ github.workspace }}/docker-entrypoint.sh:/docker-entrypoint.sh \
            -v ${{ github.workspace }}/patch.d/:/patch.d/ \
            -v ${{ github.workspace }}/.config:/build_config \
            gcc:${GCC_VERSION_MAJOR} "/docker-entrypoint.sh"

      - name: prepare artifact
        run: |
          cd ${{ github.workspace }}
          sudo du -h --max-depth=1
          tree .
          VMLINUX_PATH="$(find . -name *vmlinux)"
          BZIMAGE_PATH="$(find . -name *bzImage)"
          KO_PATH="$(find . -name *.ko)"
          CONFIG_PATH="$(find . -name *.config)"
          tar -cvf - $VMLINUX_PATH $BZIMAGE_PATH $KO_PATH $CONFIG_PATH | zstd - -o linux-${{ matrix.version }}.tar.zst 

      - name: Artifact
        uses: actions/upload-artifact@v3
        with:
          name: linux-${{ matrix.version }}
          path: ${{ github.workspace }}/linux-${{ matrix.version }}.tar.zst